---
name: Tests
'on':
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.1.8
          gemfile: Gemfile
        - ruby: 2.3.8
          gemfile: Gemfile
        - ruby: 2.4.5
          gemfile: Gemfile
        - ruby: 2.5.3
          gemfile: Gemfile
        - ruby: 2.6.1
          gemfile: Gemfile
    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    steps:
    - uses: actions/checkout@v2
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Bundle
      run: |
        gem install bundler:1.17.2
        bundle install --no-deployment
    - name: Run tests
      run: bundle exec rspec
